### ISSUE TITLE
/public/img/header-bg.jpg 교체 불가능 현상

### ISSUE THREAD

**Issue by ChangwooLim** [zarathucorp/zarathu#12]
/public/img/header-bg.jpg 교체 불가능 현상이 발생하고 있습니다.
교체 해도 이 전 이미지가 나타납니다. 해결 방법을 알아보겠습니다.

**Comment by jinseob2kim** [comment]
파일명을 다른걸로 해보시겠어요?
예) header-bg1.jpg

**Comment by ChangwooLim** [comment]
header_bg.jpg로 해 보았는데 그 파일은 정상적으로 나타납니다. Netlify에서 캐시 초기화해도 마찬가지입니다.

**Comment by ChangwooLim** [comment]
https://zarathumaintest.netlify.app/img/header_bg.jpg
https://zarathumaintest.netlify.app/img/header-bg.jpg

<img width="1440" alt="스크린샷 2021-07-05 오후 7 07 18" src="https://user-images.githubusercontent.com/86377226/124455178-3952fa80-ddc4-11eb-8507-caf8762a9051.png">

위 링크 두개와 아래 사진을 비교 해 보시면 확연히 드러납니다.

**Comment by jinseob2kim** [comment]
위 그림 홈페이지 적용했습니다.  https://www.zarathu.com/
