### ISSUE TITLE
Contact us 삭제

### ISSUE THREAD

**Issue by ChangwooLim** [zarathucorp/zarathu#4]
<img width="1189" alt="스크린샷 2021-07-04 오전 2 20 29" src="https://user-images.githubusercontent.com/86377226/124362170-68575800-dc6e-11eb-9fa1-ba6b2afc7ec9.png">

**Comment by jinseob2kim** [comment]
구글설문버튼도 다른것으로 대체 혹은 삭제하면 좋겠네요. channel io버튼을 여기에 놓을순 없나요?

**Comment by ChangwooLim** [comment]
channel.io 버튼을 구글 설문 자리에 놓으라는 말씀이신가요? 한번 알아보겠습니다.
참고로, zarathu.channel.io 링크로 우리 회사 채널톡 접근이 가능합니다.
만약 Contact us 자리에 Channel.io 버튼을 놓으라는 뜻이시면 레이아웃이 어색해질 것 같습니다.

**Comment by jinseob2kim** [comment]
> channel.io 버튼을 구글 설문 자리에 놓으라는 말씀이신가요? 한번 알아보겠습니다.
> 참고로, zarathu.channel.io 링크로 우리 회사 채널톡 접근이 가능합니다.
> 만약 Contact us 자리에 Channel.io 버튼을 놓으라는 뜻이시면 레이아웃이 어색해질 것 같습니다.

구글 설문자리에 넣는 것을 생각했는데, 설문 내용을 바꿔서 유지하는 것도 괜찮아보여 고민입니다.
- 자유로운 형식의 채팅 VS 형식을 미리 정해주는 설문 
- 마케팅팀이 결정하고 진행하시면 따르겠습니다.
